### ISSUE TITLE
Unable to delete temp directory in Elin when saving

### ISSUE THREAD

**Issue by Xerxes-2** [Whisky-App/Whisky#1251]
### Description

When playing Elin, the game failed to delete directory recursively when saving which lead to an unhandled exception.
Elin is a Unity game running Mono as the script engine. It leaves an error log (`\\?\C:\users\crossover\AppData\LocalLow\Lafrontier\Elin\Player.log`) like this:

```log
Exception:System.IO.IOException: Unknown error (0x2604200) : '\\?\C:\users\crossover\AppData\LocalLow\Lafrontier\Elin\Save\_Temp\'
  at System.IO.FileSystem.RemoveDirectoryRecursive (System.String fullPath, Interop+Kernel32+WIN32_FIND_DATA& findData, System.Boolean topLevel) [0x00163] in <7e05db41a20b45108859fa03b97088d4>:0 
  at System.IO.FileSystem.RemoveDirectory (System.String fullPath, System.Boolean recursive) [0x00036] in <7e05db41a20b45108859fa03b97088d4>:0 
  at System.IO.DirectoryInfo.Delete (System.Boolean recursive) [0x00000] in <7e05db41a20b45108859fa03b97088d4>:0 
  at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Delete(bool)
  at IO.DeleteDirectory (System.String path) [0x00018] in <af2754ac36984452b76479915f27b6cf>:0 
  at Core.OnApplicationQuit () [0x00099] in <a9cf46e3abf7419aaed33882c46a12b7>:0 
InvalidOperationException: Steamworks is not initialized.
  at Steamworks.InteropHelp.TestIfAvailableClient () [0x0001d] in <f1d22be16acd4b72a981f66c7bf5b3c7>:0 
  at Steamworks.SteamInput.Shutdown () [0x00000] in <f1d22be16acd4b72a981f66c7bf5b3c7>:0 
  at HeathenEngineering.SteamworksIntegration.API.Input+Client.Shutdown () [0x00006] in <8782cc4fc51c476ab91945a22199f345>:0 
  at HeathenEngineering.SteamworksIntegration.API.App.Application_quitting () [0x00068] in <8782cc4fc51c476ab91945a22199f345>:0 
  at UnityEngine.Application.Internal_ApplicationQuit () [0x0000d] in <f90b5d60566c42cc8b1d1412300b3616>:0 
```

The error code changes every time I launched the game, but persists along the whole program lifecycle.

I dig into `WINEDEBUG` and got these logs

```log
1044941.610:0668:066c:trace:file:NtQueryDirectoryFile => 0x80000006 (0)
1044941.610:0668:066c:Ret  ntdll.NtQueryDirectoryFile() retval=80000006 ret=7b01a3cd
1044941.610:0668:066c:Call ntdll.RtlNtStatusToDosError(80000006) ret=7b01a4a0
1044941.610:0668:066c:Ret  ntdll.RtlNtStatusToDosError() retval=00000012 ret=7b01a4a0
1044941.610:0668:066c:Call ntdll.NtClose(00000b68) ret=7b0643d5
1044941.610:0668:066c:Ret  ntdll.NtClose() retval=00000000 ret=7b0643d5
1044941.610:0668:066c:Ret  KERNEL32.FindNextFileW() retval=00000000 ret=10c554a4d
1044941.610:0668:06fc:Ret  ntdll.NtDelayExecution() retval=00000000 ret=7b084d7c
1044941.610:0668:06fc:Ret  KERNEL32.Sleep() retval=00000000 ret=18143ebea
1044941.610:0668:06fc:Call KERNEL32.QueryPerformanceCounter(66e8fd18) ret=18143eb94
1044941.610:0668:06fc:Ret  KERNEL32.QueryPerformanceCounter() retval=00000001 ret=18143eb94
1044941.610:0668:06fc:Call KERNEL32.QueryPerformanceFrequency(66e8fd20) ret=18143eba3
1044941.610:0668:06fc:Ret  KERNEL32.QueryPerformanceFrequency() retval=00000001 ret=18143eba3
1044941.610:0668:06fc:Call KERNEL32.QueryPerformanceCounter(66e8fd08) ret=18143eb94
1044941.610:0668:06fc:Ret  KERNEL32.QueryPerformanceCounter() retval=00000001 ret=18143eb94
1044941.610:0668:06fc:Call KERNEL32.QueryPerformanceFrequency(66e8fd10) ret=18143eba3
1044941.610:0668:06fc:Ret  KERNEL32.QueryPerformanceFrequency() retval=00000001 ret=18143eba3
1044941.610:0668:06fc:Call KERNEL32.Sleep(0000000a) ret=18143ebea
1044941.610:0668:06fc:Call ntdll.NtDelayExecution(00000000,66e8fcb8) ret=7b084d7c
1044941.610:0668:066c:Call KERNEL32.FormatMessageW(00003200,00000000,0066c200,00000000,0010cef0,00000100,00000000) ret=10c5561e1
1044941.610:0668:066c:trace:nls:FormatMessageW (0x3200,0000000000000000,0x66c200,0x0,000000000010CEF0,256,0000000000000000)
```

Previous log shows anything other than the dir itself was deleted successfully and `NtQueryDirectoryFile` return `0x80000006` which is `STATUS_NO_MORE_FILES` and translated to DOS Error `0x00000012` which is `ERROR_NO_MORE_FILE`.
These were all expected, but later  a message `0x0066c200` came from no where and got return to Mono, which is the error code shown in Mono log (these two logs aren't in the same session so not the same error code)

This leads to the directory empty but not deleted, and the game gets stuck. Manually deleting the dir could get the game running again but doesn't work if exception occurs in autosave, restart is need and will cause some in-game logic bug.

### Steps to reproduce

1. Create a new Windows 10 bottle
2. Download steam
3. Download Elin Demo
4. Log into game, if not seeing menu characters, it's a font issue, just click the top button which is New Game.
5. Make a new character and start game.
6. Hold `Ctrl` to skipping opening.
7. The game will stuck after starting dialog, when trying to deleting a temporary dir under save dir `C:\users\crossover\AppData\LocalLow\Lafrontier\Elin\Save`.

### Expected behaviour

Temp dirs can be deleted successfully without exception when saving.

### Logs

```bash
Whisky Version: 2.3.4
Date: 2024-12-06T08:01:34Z
macOS Version: 15.1.1

Bottle Name: Isaac
Bottle URL: /Users/xerxes2/Library/Containers/com.isaacmarovitz.Whisky/Bottles/1EEEAB6A-2C77-4B83-A451-719C4E88773F

WhiskyWine Version: 2.4.5
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/xerxes2/Library/Containers/com.isaacmarovitz.Whisky/Bottles/1EEEAB6A-2C77-4B83-A451-719C4E88773F/drive_c/Program Files (x86)/Steam/steamapps/common/Elin/Elin.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/xerxes2/Library/Containers/com.isaacmarovitz.Whisky/Bottles/1EEEAB6A-2C77-4B83-A451-719C4E88773F";
}

0798:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by HackingU0** [comment]
As I reported this bug to Noacat (Maker of Elin), it should be fixed on 2025.1 update. Should close this issue

**Comment by HackingU0** [comment]
Just tested. It fixed

**Comment by HackingU0** [comment]
But a new issue came out. I don't think this related to Whisky or the translation. It's probably Elin uses Bepinx and that's a issue related with Bepinx.

**Comment by Xerxes-2** [comment]
Seems like Noacat introduced an Error handling so the game won't just hang. But the problem persist, we still need to manually delete the Temp dirs.

**Comment by Xerxes-2** [comment]
I made a small program to automatically delete empty dirs inside save dir. So if game failed to autosave, just manually save it again and it program will handle all the hassle.

```rust
use anyhow::{Context, Result};
use log::{error, info, warn};
use notify::{Event, RecursiveMode, Watcher};
use std::{sync::mpsc, thread};

fn handle_event(event: notify::Event, path: &std::path::Path) -> Result<()> {
    if event.need_rescan() {
        warn!("Some events may be lost.");
    }
    let event_path = event.paths.get(0).context("No path")?.strip_prefix(path)?;
    let event_path_parent = event_path.parent().context("No parent")?;
    if event.kind.is_remove() {
        warn!("Removed: {:?}", event_path);
        if event_path_parent.read_dir()?.next().is_none() {
            warn!("Removing parent: {:?}", event_path_parent);
            std::fs::remove_dir(event_path_parent)?;
        }
    } else {
        info!("Event {:?}: {:?}", event.kind, event_path);
    }
    Ok(())
}

fn main() -> Result<()> {
    env_logger::builder()
        .filter(Some("elin_helper"), log::LevelFilter::Info)
        .format_timestamp(None)
        .format_target(false)
        .init();
    let args: Vec<String> = std::env::args().collect();
    let target = args.get(1).map(|s| s.as_str()).unwrap_or(".");
    let full_path = std::path::Path::new(target);
    // change to target directory
    std::env::set_current_dir(full_path)?;
    let path = std::path::Path::new(".");
    for entry in std::fs::read_dir(path)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            if path.read_dir()?.next().is_none() {
                std::fs::remove_dir(&path)?;
                info!("Removed: {:?}", path.strip_prefix(&path).unwrap());
            }
        }
    }
    let (tx, rx) = mpsc::channel::<notify::Result<Event>>();

    let mut watcher = notify::recommended_watcher(tx)?;
    watcher.watch(path, RecursiveMode::Recursive)?;
    info!("Watching: {:?}", full_path);
    thread::scope(|s| {
        for res in rx {
            match res {
                Ok(event) => {
                    s.spawn(move || {
                        handle_event(event, full_path).unwrap_or_else(|e| error!("{:?}", e));
                    });
                }
                Err(e) => {
                    error!("{:?}", e);
                }
            }
        }
    });
    Ok(())
}
```

**Comment by HackingU0** [comment]
https://github.com/HackingU0/elin_save_watchdog
This should solve all the problem and won't hurt the savefile
